[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "extractrs"
dynamic = ["version"]
description = "Fast exact zonal statistics for xarray — powered by Rust"
readme = "README.md"
license = { text = "Apache-2.0" }
requires-python = ">=3.9"
dependencies = [
    "numpy",
    "xarray",
    "geopandas",
]

[project.optional-dependencies]
rio = ["rioxarray"]

[tool.maturin]
python-source = "python"
module-name = "extractrs._extractrs"
features = ["pyo3/extension-module"]
